### ISSUE TITLE
neither package.json nor .sense-go.yml available

### ISSUE THREAD

**Issue by countnazgul** [stefanwalther/sense-go#31] opened 2016-09-06 02:33 UTC
I'm trying to start and use sense-go but for some reason i cant. I've made the same folder structure and placed package.json file in the root folder but when i try to start sense-go im getting:

```
[03:24:44] Using the default sense-go settings                                                                                                                                                    
[03:24:44]      neither package.json nor .sense-go.yml available) ...                                                                                                                             
[03:24:44] sense-go does not provide any default task out of the box. 
```

I've copied the default yml config file and then i'm getting:

```
[03:25:53] Using the .sense-go.local.yml file ...                                                                                                                                                 
[03:25:53] sense-go does not provide any default task out of the box.   
```

Is there anything else that need to be done after the initial installation or there is another step that im missing while i've prepared the project?

**Comment by changeling76** [comment] 2017-02-05 19:50
confirm. same to me. Neither package.json nor yml config file helps.

**Comment by stefanwalther** [comment] 2017-04-11 11:33
@countnazgul Instead of running

```$
$ sense-go
```

run 

```
$ sense-go build
```

`build` is the task.

**Comment by stefanwalther** [comment] 2017-05-10 13:49
@countnazgul: ping, could you test it?

**Comment by stefanwalther** [comment] 2017-06-19 12:57
Closing as I cannot reproduce it. @countnazgul: Feel free to re-open if needed.

**Closed as completed by stefanwalther** 2017-06-19 12:57 UTC
Labels: type:bug, awaiting-answer
